config:
  style: css
  output_path: output/stylesheets/android_icons
  image_output_path: output/images/sprites/
  source_path: resources/images/
  class_separator: '_'
  default_format: png

# defines what sprite collections get created
images:    
  - name: android_icons
    format: png
    align: vertical
    spaced_by: 50
    sources:
      - android_icons/*.png