config:
  style: css
  style_output_path: output/stylesheets/android-icons
  image_output_path: output/images/sprites/
  image_source_path: resources/images/
  public_path: ''
  class_separator: '-'
  default_format: png

# defines what sprite collections get created
images:    
  - name: android-icons
    format: png
    align: vertical
    spaced_by: 50
    sources:
      - android-icons/*.png